version: '3.4'
services:
  muon-discord-bot:
    container_name: muon-verify-node
    image: muon-verify-node
    restart: always
    build:
      context: .
      network: host

    network_mode: host

    ports:
      - 3004:3004
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tehran
      - NODE_ENV=production
      - BUILD_MODE=production
    command: node .output/server/index.mjs
